# Generated by Django 5.2.7 on 2025-10-16 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicamento', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('categoria', models.CharField(choices=[('analgesico', 'Analgésico'), ('antibiotico', 'Antibiótico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antihistaminico', 'Antihistamínico'), ('cardiovascular', 'Cardiovascular'), ('digestivo', 'Digestivo'), ('respiratorio', 'Respiratorio'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(default=10, verbose_name='Stock mínimo')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('uso_frecuente', models.BooleanField(default=False, verbose_name='Uso frecuente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
