# Generated by Django 5.2.7 on 2025-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(choices=[('analgesico', 'Analgésico'), ('antibiotico', 'Antibiótico'), ('antiinflamatorio', 'Antiinflamatorio'), ('antihistaminico', 'Antihistamínico'), ('cardiovascular', 'Cardiovascular'), ('digestivo', 'Digestivo'), ('respiratorio', 'Respiratorio'), ('rehidratante', 'Rehidratante'), ('antiseptico', 'Antiséptico'), ('gastroprotector', 'Gastroprotector'), ('antialergico', 'Antialérgico'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría'),
        ),
    ]
